services:
  project:
    build: project
    ports:
      - "8080:8080"
    platform: linux/amd64
    networks:
      - spring-network

  compiler:
    build: compiler
    ports:
      - "8082:8082"
    platform: linux/amd64
    networks:
      - spring-network

  ui:
    build: ui
    ports:
      - "8083:8083"
    platform: linux/amd64
    networks:
      - spring-network

  dark-mode:
    build: dark-mode
    ports:
      - "8081:8081"
    platform: linux/amd64
    networks:
      - spring-network

networks:
  spring-network:
