version: "3.8"
services:
  project:
    image: gitlab.lrz.de:5005/ase23-brueckelsee/onlineide/project:latest
    restart: on-failure:3
    ports:
      - "8080:8080"
    platform: linux/amd64
    networks:
      - spring-network
    depends_on:
      - db
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/my_db?user=admin&password=test

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: my_db

  compiler:
    image: gitlab.lrz.de:5005/ase23-brueckelsee/onlineide/compiler
    restart: on-failure:3
    ports:
      - "8082:8082"
    platform: linux/amd64
    networks:
      - spring-network
    depends_on:
      - project
    environment:
      - PROJECT_URL=http://project:8080

  ui:
    image: gitlab.lrz.de:5005/ase23-brueckelsee/onlineide/ui:latest
    restart: on-failure:3
    ports:
      - "8083:8083"
    platform: linux/amd64
    networks:
      - spring-network
    depends_on:
      - project
      - compiler
    environment:
      - PROJECT_URL=http://project:8080
      - COMPILER_URL=http://compiler:8082

  dark-mode:
    image: gitlab.lrz.de:5005/ase23-brueckelsee/onlineide/dark-mode:latest
    restart: on-failure:3
    ports:
      - "8081:8081"
    platform: linux/amd64
    networks:
      - spring-network
    depends_on:
      - project
      - compiler
      - ui
    environment:
      - PROJECT_URL=http://project:8080
      - COMPILER_URL=http://compiler:8082
      - UI_URL=http://ui:8083

networks:
  spring-network:
