spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          gitlab:
            authorization-uri: https://gitlab.lrz.de/oauth/authorize
            token-uri: https://gitlab.lrz.de/oauth/token
            user-info-uri: https://gitlab.lrz.de/api/v4/user
            user-name-attribute: username
            jwk-set-uri: https://gitlab.lrz.de/oauth/discovery/keys
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - RewritePath=/project/(?<segment>.*), /$\{segment}
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: compiler-service
          uri: lb://compiler-service
          predicates:
            - Path=/compiler/**
          filters:
            - RewritePath=/compiler/(?<segment>.*), /$\{segment}
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: ui-service
          uri: lb://ui-service
          predicates:
            - Path=/**
          filters:
            - RewritePath=/ui/(?<segment>.*), /$\{segment}
            - TokenRelay=
            - RemoveRequestHeader=Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
  port: ${PORT:8000}
