spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - RewritePath=/project/(?<segment>.*), /$\{segment}
        - id: ui-service
          uri: lb://ui-service
          predicates:
            - Path=/**
          filters:
            - RewritePath=/ui/(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
  port: ${PORT:8000}
