spring:
  web:
    resources:
      static-locations: classpath:/static/browser
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      client:
        provider:
          gitlab:
            authorization-uri: https://gitlab.lrz.de/oauth/authorize
            token-uri: https://gitlab.lrz.de/oauth/token
            user-info-uri: https://gitlab.lrz.de/api/v4/user
            user-name-attribute: username
        registration:
          gitlab:
            provider: gitlab
            redirect-uri: http://localhost:8083/login/oauth2/code/gitlab
            authorization-grant-type: authorization_code
            client-id: e524dae9467178fa924438f243413774819266c1915243750d91234b19d0d198
            client-secret: gloas-a7c46219519888969c9d489e21cc0237fd74bfaa11e9173b9bbf61c246f91b88

server:
  port: ${PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
