spring:
  application:
    name: ui-service
  web:
    resources:
      static-locations: classpath:/static/browser
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: ${PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
