# Sets the default application profile to development
spring:
  application:
    name: project-service
  profiles:
    active: dev
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}

server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
